#!/usr/bin/env python3
"""Generate heldout golden pairs from Qdrant documents.

Claims are generated by LLM from `review_title` + `source_name` ONLY —
the `claim_text` field is intentionally withheld during generation to
avoid data leakage. This produces a genuinely held-out benchmark where
the system must match a naturally-rephrased claim against the indexed
`claim_text`.

Usage:
    # Inside Docker container:
    python3 data/seeds/generate_heldout.py [--limit N] [--dry-run]

    # Set LLM_PROVIDER=groq and GROQ_API_KEY for Groq (recommended).
    # Falls back to Ollama if not configured.

Output:
    data/benchmark/golden_pairs_heldout.json  — the heldout golden pairs
"""

from __future__ import annotations

import argparse
import asyncio
import json
import logging
import os
import random
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from qdrant_client import QdrantClient
from services.llm import LLMClient

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
logger = logging.getLogger(__name__)

BENCH_DIR = Path(__file__).resolve().parents[1] / "benchmark"
OUTPUT_FILE = BENCH_DIR / "golden_pairs_heldout.json"

# ---------------------------------------------------------------------------
# Language-specific system prompts
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """\
You are building a fact-checking benchmark. Your task is to write a realistic
claim that an ordinary person might submit to a fact-checker — based ONLY on
the article title and publisher provided. The claim should:

1. Sound like something a real person would say, share, or believe.
2. Be written in the SAME LANGUAGE as the article.
3. NOT copy the title verbatim — rephrase naturally, from the perspective of
   someone who heard or read about the topic.
4. Be 1–2 sentences maximum.
5. Output ONLY the claim text, with no explanation, quotes, or prefix.
"""

PROMPT_TEMPLATE = """\
Fact-check article:
  Title:     {title}
  Publisher: {publisher}
  Language:  {language_label}

Write a realistic claim that someone might submit to a fact-checker about this topic.\
"""

LANG_LABELS = {
    "en": "English",
    "pl": "Polish",
    "ua": "Ukrainian",
    "uk": "Ukrainian",
}

# ---------------------------------------------------------------------------
# Stance mapping
# ---------------------------------------------------------------------------

REFUTED_KEYWORDS = {
    "refuted", "false", "fake", "wrong", "incorrect", "hoax", "debunked",
    "inaccurat", "fabricat", "pants on fire", "pinocchio", "scam",
    "not true", "altered", "ai-generated",
    # Polish
    "fałsz", "fałszywe", "nieprawda", "błąd", "manipulacja",
    "raczej fałsz", "częściowy fałsz", "przerobiony",
    # Ukrainian
    "фейк", "неправда", "хибне", "брехня", "маніпуляція",
}
SUPPORTED_KEYWORDS = {
    "supported", "true", "correct", "confirmed", "verified", "accurate",
    "right",
    # Polish
    "prawda", "prawdziwe", "potwierdzone", "poprawne",
    # Ukrainian
    "правда", "підтверджено",
}
NEI_KEYWORDS = {
    "nei", "misleading", "missing context", "mixture", "unproven",
    "half true", "unsupported", "lacks context", "out of context",
    "no evidence", "exaggerat", "needs context", "distort",
    "partly", "cherry-pick",
    # Polish
    "półprawda", "brakujący kontekst", "blisko prawdy",
}

def infer_stance(rating: str) -> str:
    r = rating.strip().lower()
    # Check REFUTED first (before SUPPORTED) to avoid "not true" matching "true"
    for kw in REFUTED_KEYWORDS:
        if kw in r:
            return "REFUTED"
    for kw in NEI_KEYWORDS:
        if kw in r:
            return "NEI"
    for kw in SUPPORTED_KEYWORDS:
        if kw in r:
            return "SUPPORTED"
    return "NEI"


# ---------------------------------------------------------------------------
# Main generation logic
# ---------------------------------------------------------------------------

async def generate_claim(llm: LLMClient, title: str, publisher: str, language: str) -> str:
    lang_label = LANG_LABELS.get(language, "English")
    prompt = PROMPT_TEMPLATE.format(
        title=title.strip(),
        publisher=publisher.strip(),
        language_label=lang_label,
    )
    claim = await llm.generate(
        prompt=prompt,
        system_prompt=SYSTEM_PROMPT,
        temperature=0.7,   # some variation
        max_tokens=128,
    )
    return claim.strip().strip('"').strip("'")


async def main(limit_per_lang: int, dry_run: bool) -> None:
    client = QdrantClient(host="qdrant", port=6333)
    col_name = "fact_checks"

    # Scroll all docs
    all_docs = []
    offset = None
    while True:
        batch, offset = client.scroll(
            col_name, limit=100, offset=offset,
            with_payload=True, with_vectors=False
        )
        all_docs.extend(batch)
        if offset is None:
            break

    logger.info("Loaded %d docs from Qdrant", len(all_docs))

    # Filter: must have review_title (non-empty)
    usable = [d for d in all_docs if d.payload.get("review_title", "").strip()]
    logger.info("Docs with review_title: %d", len(usable))

    # Group by language
    by_lang: dict[str, list] = {}
    for d in usable:
        lang = d.payload.get("language", "en")
        if lang == "uk":
            lang = "ua"   # normalise
        by_lang.setdefault(lang, []).append(d)

    logger.info("Language groups: %s", {k: len(v) for k, v in by_lang.items()})

    # Sample docs per language (use all if fewer than limit)
    random.seed(42)
    selected: list = []
    for lang, docs in by_lang.items():
        n = min(limit_per_lang, len(docs))
        sample = random.sample(docs, n)
        selected.extend(sample)
        logger.info("Selected %d docs for lang=%s", n, lang)

    logger.info("Total selected: %d docs", len(selected))

    if dry_run:
        logger.info("DRY RUN — showing first 5 titles and exiting.")
        for d in selected[:5]:
            p = d.payload
            print(f"  [{p.get('language')}] {p.get('review_title','')[:80]}")
        return

    llm = LLMClient()
    logger.info("LLM provider: %s", llm.provider)

    pairs = []
    errors = 0

    for i, doc in enumerate(selected):
        p = doc.payload
        lang = p.get("language", "en")
        if lang == "uk":
            lang = "ua"

        title = p.get("review_title", "").strip()
        publisher = p.get("source_name", "fact-checker").strip()
        claim_text = p.get("claim_text", "").strip()
        source_url = p.get("source_url", "").strip()
        rating = p.get("review_rating", "").strip()
        pub_date = p.get("published_at", "")

        pair_id = f"heldout_{lang}_{i+1:03d}"

        logger.info("[%d/%d] %s  %s", i + 1, len(selected), pair_id, title[:60])

        try:
            claim = await generate_claim(llm, title, publisher, lang)
        except Exception as exc:
            logger.warning("LLM error for %s: %s — skipping", pair_id, exc)
            errors += 1
            continue

        stance = infer_stance(rating)

        pair = {
            "id": pair_id,
            "claim": claim,
            "expected_match": claim_text,   # the verbatim text in Qdrant
            "expected_stance": stance,
            "language": lang,
            "source": publisher,
            "expected_source_url": source_url,
            "review_title": title,          # kept for transparency / audit
            "review_rating": rating,
            "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
            "generation_method": "llm_from_title",
        }
        pairs.append(pair)

        # Small progress save every 25
        if len(pairs) % 25 == 0:
            _save(pairs, OUTPUT_FILE)
            logger.info("Progress save: %d pairs written", len(pairs))

    _save(pairs, OUTPUT_FILE)

    # Print summary
    from collections import Counter
    lang_counts = Counter(p["language"] for p in pairs)
    stance_counts = Counter(p["expected_stance"] for p in pairs)
    print("\n" + "=" * 60)
    print(f"  Heldout pairs generated: {len(pairs)}")
    print(f"  Errors / skipped:        {errors}")
    print(f"  By language:  {dict(lang_counts)}")
    print(f"  By stance:    {dict(stance_counts)}")
    print(f"  Saved to:     {OUTPUT_FILE}")
    print("=" * 60)


def _save(pairs: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(pairs, f, indent=2, ensure_ascii=False)


# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate heldout golden pairs")
    parser.add_argument(
        "--limit", type=int, default=80,
        help="Max docs to sample per language (default: 80)"
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print selected titles without calling LLM"
    )
    args = parser.parse_args()

    asyncio.run(main(limit_per_lang=args.limit, dry_run=args.dry_run))
